# Generated by Django 3.0 on 2019-12-27 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EXTRA', '0002_coordonnees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='numéro')),
                ('adress', models.CharField(max_length=254, verbose_name='nom de la voie')),
                ('code_postal', models.PositiveIntegerField(verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
