# Generated by Django 3.0 on 2019-12-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXTRA', '0004_auto_20191227_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='user_id',
        ),
    ]
