# Generated by Django 3.0 on 2019-12-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXTRA', '0006_adresstoetablissement_adresstouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdressToEtablissement',
        ),
    ]
