# Generated by Django 3.0 on 2020-01-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EXTRA', '0007_delete_adresstoetablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresstouser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
