# Generated by Django 3.0 on 2020-01-04 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EXTRA', '0008_auto_20200104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresstouser',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressa', to='EXTRA.Adress', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adresstouser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressu', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
