# Generated by Django 3.0 on 2020-01-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXTRA', '0009_auto_20200104_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresstouser',
            old_name='user_id',
            new_name='user',
        ),
    ]
