# Generated by Django 3.0 on 2020-01-09 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EXTRA', '0010_auto_20200104_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresstouser',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='EXTRA.Adress', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adresstouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
