# Generated by Django 3.0 on 2019-12-27 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EXTRA', '0003_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Métier')),
                ('taux_horaire_normal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux horaire')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='METIER.Corporation', verbose_name='Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseigne', models.CharField(max_length=100, verbose_name='Enseigne')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EXTRA.Adress', verbose_name='Adresse')),
                ('gerant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerant', to=settings.AUTH_USER_MODEL, verbose_name='Gérant')),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprio', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
    ]
