# Generated by Django 3.0 on 2019-12-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('METIER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='METIER.Corporation', verbose_name='Corporation'),
        ),
    ]
