# Generated by Django 3.0 on 2019-12-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EXTRA', '0007_delete_adresstoetablissement'),
        ('METIER', '0003_remove_etablissement_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressToEtablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXTRA.Adress', verbose_name='Adresse')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='METIER.Etablissement', verbose_name='Etbalissement')),
            ],
        ),
    ]
