# Generated by Django 3.0 on 2019-12-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('METIER', '0004_adresstoetablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='valide',
            field=models.BooleanField(default=1, verbose_name='Validé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresstoetablissement',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='METIER.Etablissement', verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='corporation',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='METIER.Corporation', verbose_name='Corporation'),
        ),
    ]
