# Generated by Django 3.0 on 2019-12-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('METIER', '0005_auto_20191227_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='corporation',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='METIER.Corporation', verbose_name='Corporation'),
        ),
    ]
