# Generated by Django 3.0 on 2019-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('METIER', '0006_auto_20191227_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='taux_horaire_special',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='taux horaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
    ]
