# Generated by Django 3.0 on 2020-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('METIER', '0007_auto_20191227_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metier',
            name='taux_horaire_special',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux horaire spécial'),
        ),
    ]
